// <auto-generated/>
using Microsoft.AspNetCore.Components;
using pax.chess;
using System.Text;

namespace pax.BlazorChess.Shared.Components;

public partial class ClockComponent : ComponentBase, IChessClockDisplay
{
    private TimeSpan _whiteTime;
    private TimeSpan _blackTime;
    private PieceColor? _activeColor;
    private PieceColor? _timedOutColor;

    public void OnClockUpdated(TimeSpan whiteTime, TimeSpan blackTime, PieceColor? activeColor)
    {
        _whiteTime = whiteTime;
        _blackTime = blackTime;
        _activeColor = activeColor;
        InvokeAsync(StateHasChanged);
    }

    public void OnTimeout(PieceColor timedOutColor)
    {
        _timedOutColor = timedOutColor;
        InvokeAsync(StateHasChanged);
    }

    private string GetCssClass(PieceColor color)
    {
        bool isActive = _activeColor == color;
        bool isTimedOut = _timedOutColor == color;
        bool isShortOnTime = (color == PieceColor.White && _whiteTime.TotalSeconds < 30) ||
                        (color == PieceColor.Black && _blackTime.TotalSeconds < 30);
        StringBuilder sb = new();
        sb.Append(color == PieceColor.White ? "clock white" : "clock black");
        if (isActive)
            sb.Append(" active");
        if (isTimedOut)
            sb.Append(" timed-out");
        else if (isShortOnTime)
            sb.Append(" short-on-time");
        return sb.ToString();
    }
}